packages:
  - 'red-dot'
  - 'red-dot-vue'
  - 'red-dot-react'
  - 'vue-playground'
  - 'react-playground'

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.16
    '@types/react-dom': ^19.1.9
  vue3:
    vue: ^3.5.22
